#ifndef __ST_CODES_H__
#define __ST_CODES_H__

typedef enum {
    OK,
    NO_MEMORY,
    NO_FILE,
    INVALID_PARAMETER,
    INVALID_BRACKET,
    EMPTY_BRACKET,
    ZERO_SIZE,
    DIVIDE_BY_ZERO,
    NEGATIVE_MOD,
    NEGATIVE_POWER,
    NOT_DIGIT_OR_OPERATOR,
    UNUSED_DIGITS_OR_OPERATORS
} status_codes;

#endif
